#!/usr/bin/env node
/**
 * Manifesto generator — zero dependencies, plain Node.
 *
 * Edit content in manifesto/content/*.json, then run:
 *   node manifesto/build.js
 *
 * Generates (never hand-edit these):
 *   public/index.html            EN
 *   public/<lang>/index.html     each translation
 *
 * Deliberately does NOT generate public/llms.txt or the README manifesto
 * section. Both are hand-written and carry material that has no source in
 * these JSON files (llms.txt has its own summary, Meetups and Links
 * sections; the README has its own emphasis and structure). Generating them
 * would clobber good prose to solve a drift risk that only bites when the
 * manifesto text itself changes — which is rare, and caught by review.
 *
 * The canonical English pair shown under each translated pair is read from
 * en.json at build time — translations never restate it, so it cannot drift.
 */

const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const CONTENT = path.join(__dirname, 'content');
const PUBLIC = path.join(ROOT, 'public');
const ORIGIN = 'https://agentic-shift.com';
const BANNER = '<!-- GENERATED by manifesto/build.js from manifesto/content/{lang}.json — do not edit by hand. -->';

// Order defines the language switcher order. `en` must come first: it is the
// canonical source for the English pairs and for llms.txt / README.
// A language appears on the site only once content/<lang>.json exists, so a
// translation in progress is simply absent rather than half-rendered.
const ALL_LANGS = ['en', 'de', 'nl', 'fr', 'it', 'es', 'pt', 'cs', 'uk', 'ru', 'zh', 'ja'];
const LANGS = ALL_LANGS.filter((l) => fs.existsSync(path.join(__dirname, 'content', `${l}.json`)));

const missing = ALL_LANGS.filter((l) => !LANGS.includes(l));
if (!LANGS.includes('en')) throw new Error('content/en.json is required — it is the canonical source.');

const OG_LOCALE = {
  en: 'en_US', de: 'de_DE', nl: 'nl_NL', fr: 'fr_FR', it: 'it_IT',
  es: 'es_ES', pt: 'pt_PT', cs: 'cs_CZ', uk: 'uk_UA', ru: 'ru_RU',
  zh: 'zh_CN', ja: 'ja_JP',
};

// Wording for the switcher's aria-label, per language.
const LANGBAR_LABEL = {
  en: 'Language', de: 'Sprache', nl: 'Taal', fr: 'Langue', it: 'Lingua',
  es: 'Idioma', pt: 'Idioma', cs: 'Jazyk', uk: 'Мова', ru: 'Язык',
  zh: '语言', ja: '言語',
};

const read = (p) => fs.readFileSync(p, 'utf8');
const load = (lang) => JSON.parse(read(path.join(CONTENT, `${lang}.json`)));

const all = Object.fromEntries(LANGS.map((l) => [l, load(l)]));
const en = all.en;
const template = read(path.join(__dirname, 'template.html'));

const esc = (s) => String(s)
  .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
  .replace(/"/g, '&quot;');

const entities = (s) => s
  .replace(/&amp;/g, '&').replace(/&lt;/g, '<').replace(/&gt;/g, '>')
  .replace(/&quot;/g, '"').replace(/&#39;/g, "'");

// Convert the inline HTML used in content values to plain text or markdown,
// for the llms.txt / README manifesto blocks. `emphasis`: 'md' renders
// definition/strong as **bold** and amber/em as *italic*; 'none' strips them.
// `links`: 'md' → [text](url); 'paren' → text (url). A sentinel pass collapses
// nested bold/italic (e.g. a <strong> wrapping a definition span) into a single
// pair, so the markdown never emits broken **…**…** runs.
const B_OPEN = String.fromCharCode(0xE000);
const B_CLOSE = String.fromCharCode(0xE001);
const I_OPEN = String.fromCharCode(0xE002);
const I_CLOSE = String.fromCharCode(0xE003);

function inline(html, { emphasis, links }) {
  let s = String(html);
  s = s.replace(/<a\b[^>]*href="([^"]+)"[^>]*>([\s\S]*?)<\/a>/g,
    links === 'md' ? '[$2]($1)' : '$2 ($1)');
  s = s.replace(/<span class="definition">([\s\S]*?)<\/span>/g, B_OPEN + '$1' + B_CLOSE);
  s = s.replace(/<span class="amber">([\s\S]*?)<\/span>/g, I_OPEN + '$1' + I_CLOSE);
  s = s.replace(/<strong>/g, B_OPEN).replace(/<\/strong>/g, B_CLOSE);
  s = s.replace(/<em>/g, I_OPEN).replace(/<\/em>/g, I_CLOSE);
  s = s.replace(/<[^>]+>/g, '');           // drop any remaining tags (e.g. <span class="lite">)
  s = entities(s);

  let out = '';
  let bold = 0;
  let ital = 0;
  const bMark = emphasis === 'md' ? '**' : '';
  const iMark = emphasis === 'md' ? '*' : '';
  for (const ch of s) {
    if (ch === B_OPEN) { if (bold === 0) out += bMark; bold++; }
    else if (ch === B_CLOSE) { bold = Math.max(0, bold - 1); if (bold === 0) out += bMark; }
    else if (ch === I_OPEN) { if (ital === 0) out += iMark; ital++; }
    else if (ch === I_CLOSE) { ital = Math.max(0, ital - 1); if (ital === 0) out += iMark; }
    else out += ch;
  }
  return out.replace(/\s+/g, ' ').trim();
}

function hreflang() {
  const rows = LANGS.map((l) =>
    `  <link rel="alternate" hreflang="${l}" href="${ORIGIN}${all[l].dir}">`);
  rows.push(`  <link rel="alternate" hreflang="x-default" href="${ORIGIN}${en.dir}">`);
  return rows.join('\n');
}

function langbar(current) {
  return LANGS.map((l) => {
    const c = all[l];
    const active = l === current ? ' aria-current="page"' : '';
    return `      <a href="${c.dir}" hreflang="${l}" lang="${l}"${active}>${esc(c.name)}</a>`;
  }).join('\n');
}

function pair(s, ref, isEn) {
  // English page: plain pair, no gloss (stays identical to the canonical page).
  if (isEn) {
    return `<p class="pair"><span class="from">${esc(s.from)}</span>`
      + `<span class="arrow" aria-hidden="true">→</span>`
      + `<span class="to">${esc(s.to)}</span></p>`;
  }
  // Translated page: each term stacks its canonical English word directly
  // beneath it — sourced from en.json, so the gloss can never drift.
  const term = (cls, word, gloss) =>
    `<span class="term"><span class="${cls}">${esc(word)}</span>`
    + `<span class="pair-en" lang="en">${esc(gloss)}</span></span>`;
  return `<p class="pair">`
    + term('from', s.from, ref.from)
    + `<span class="arrow" aria-hidden="true">→</span>`
    + term('to', s.to, ref.to)
    + `</p>`;
}

// The shifts render in groups (technical → Field Guide, organizational →
// 10X ORG). Grouping is structure, not copy: `accent`, `count` and `href`
// live in en.json only and are read from there for every language, so a
// translation supplies just the localized `label` + `link` text and the
// grouping can never drift.
// Missing fields fall back to English rather than rendering "undefined", so a
// half-translated group still ships a readable page; parityDrift() names the
// gap and fails the build.
const localGroup = (c, gi) => ({ ...en.groups[gi], ...((c.groups && c.groups[gi]) || {}) });

// Group index a shift opens, or -1 if it sits mid-group. Used by the Markdown
// emitters to slot a group heading in front of the right shift.
function groupOpening(i) {
  let start = 0;
  for (let gi = 0; gi < en.groups.length; gi++) {
    if (i === start) return gi;
    start += en.groups[gi].count;
  }
  return -1;
}

function shifts(c) {
  const isEn = c.lang === 'en';
  let start = 0;
  return en.groups.map((g, gi) => {
    const loc = localGroup(c, gi);
    const first = start;
    start += g.count;
    const items = c.shifts.slice(first, first + g.count).map((s, k) => {
      const n = String(first + k + 1).padStart(2, '0');
      return `        <li class="shift">
          <span class="n" aria-hidden="true">${n}</span>
          <div class="shift-body">
            ${pair(s, en.shifts[first + k], isEn)}
            <p class="note">${s.note}</p>
          </div>
        </li>`;
    }).join('\n\n');
    return `    <section class="group group-${g.accent}">
      <p class="group-head">
        <span class="group-label">${esc(loc.label)}</span>
        <a class="group-src" href="${esc(g.href)}" target="_blank" rel="noopener"><span class="src-by">${esc(loc.by)}</span> ${esc(loc.link)}<span class="ext" aria-hidden="true">↗</span></a>
      </p>

      <ol class="shifts" start="${first + 1}">

${items}

      </ol>
    </section>`;
  }).join('\n\n');
}

const lede = (c) => c.lede.map((p) => `    <p class="lede">${p}</p>`).join('\n\n');

const qa = (c) => c.qa.map((x) =>
  `    <p class="q-head"><span class="p" aria-hidden="true">&gt;</span> ${esc(x.q)}</p>\n\n    <p class="lede">${x.a}</p>`
).join('\n\n');

function render(c) {
  const map = {
    LANG: c.lang,
    DIR: c.dir,
    OG_LOCALE: OG_LOCALE[c.lang],
    LANGBAR_LABEL: esc(LANGBAR_LABEL[c.lang]),
    LANGBAR: langbar(c.lang),
    HREFLANG: hreflang(),
    META_TITLE: esc(c.meta.title),
    META_DESCRIPTION: esc(c.meta.description),
    META_KEYWORDS: esc(c.meta.keywords),
    META_OG_TITLE: esc(c.meta.ogTitle),
    META_OG_DESCRIPTION: esc(c.meta.ogDescription),
    META_SCHEMA_DESCRIPTION: esc(c.meta.schemaDescription),
    META_LLMS_TITLE: esc(c.meta.llmsTitle),
    HEADLINE_LEAD: esc(c.hero.headlineLead),
    HEADLINE_GLITCH: esc(c.hero.headlineGlitch),
    SUBTITLE: esc(c.hero.subtitle),
    LEDE: lede(c),
    SECTION_HEAD: c.sectionHead,
    QA_HEAD: esc(c.qaHead),
    SHIFTS: shifts(c),
    // Synthesis note below the shifts (links the two technical + three
    // structural shifts to the Field Guide). Array of paragraphs; absent until
    // a language adds it.
    SYSTEM_NOTE: c.systemNote
      ? [].concat(c.systemNote).map((p) => `    <p class="lede system-note">${p}</p>`).join('\n')
      : '',
    QA: qa(c),
    FOOT_BY: esc(c.foot.by),
    FOOT_CTA: esc(c.foot.cta),
    MD_HREF: `${c.dir}agentic-shift-${c.lang}.md`,
    MD_DOWNLOAD: `agentic-shift-${c.lang}.md`,
    MD_LANG: c.lang.toUpperCase(),
  };

  let out = template;
  for (const [k, v] of Object.entries(map)) {
    out = out.split(`{{${k}}}`).join(v);
  }

  const left = out.match(/\{\{[A-Z_]+\}\}/g);
  if (left) throw new Error(`${c.lang}: unreplaced placeholders: ${[...new Set(left)].join(', ')}`);

  return out.replace('<!DOCTYPE html>', `<!DOCTYPE html>\n${BANNER.replace('{lang}', c.lang)}`);
}

// ── sitemap.xml ───────────────────────────────────────────────────────
// Fully generated: the manifesto languages come from LANGS (so a new language
// is picked up automatically), plus the static /munich entry. Pure structure —
// nothing hand-authored to clobber.
function sitemap() {
  const alts = LANGS.map((l) =>
    `    <xhtml:link rel="alternate" hreflang="${l}" href="${ORIGIN}${all[l].dir}"/>`);
  alts.push(`    <xhtml:link rel="alternate" hreflang="x-default" href="${ORIGIN}${en.dir}"/>`);
  const altBlock = alts.join('\n');
  const entry = (loc, priority) =>
    `  <url>\n    <loc>${ORIGIN}${loc}</loc>\n${altBlock}\n`
    + `    <changefreq>monthly</changefreq>\n    <priority>${priority}</priority>\n  </url>`;
  const urls = LANGS.map((l) => entry(all[l].dir, l === 'en' ? '1.0' : '0.9'));
  urls.push(`  <url>\n    <loc>${ORIGIN}/munich</loc>\n`
    + `    <changefreq>weekly</changefreq>\n    <priority>0.8</priority>\n  </url>`);
  urls.push(`  <url>\n    <loc>${ORIGIN}/community</loc>\n`
    + `    <changefreq>weekly</changefreq>\n    <priority>0.8</priority>\n  </url>`);
  return `<?xml version="1.0" encoding="UTF-8"?>\n`
    + `<!-- GENERATED by manifesto/build.js — do not edit by hand. -->\n`
    + `<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"\n`
    + `        xmlns:xhtml="http://www.w3.org/1999/xhtml">\n`
    + `${urls.join('\n')}\n</urlset>\n`;
}

// ── llms.txt / README manifesto blocks (between markers) ──
const plain = (s) => inline(s, { emphasis: 'none', links: 'paren' });

// One language's manifesto in llms.txt plain-text style (no emphasis).
function llmsLang(c, heading) {
  const L = [heading, ''];
  c.lede.forEach((p) => { L.push(plain(p)); L.push(''); });
  L.push(`### ${plain(c.sectionHead)}`, '');
  c.shifts.forEach((s, i) => {
    const gi = groupOpening(i);
    if (gi >= 0) {
      const loc = localGroup(c, gi);
      L.push(`#### ${plain(loc.label)} — ${plain(loc.by)} ${plain(loc.link)} (${en.groups[gi].href})`, '');
    }
    const gloss = c.lang === 'en' ? '' : ` (${en.shifts[i].from} → ${en.shifts[i].to})`;
    L.push(`${i + 1}. ${s.from} → ${s.to}${gloss} — ${plain(s.note)}`);
    if (groupOpening(i + 1) >= 0) L.push('');
  });
  if (c.systemNote) [].concat(c.systemNote).forEach((p) => L.push('', plain(p)));
  L.push('', `### ${plain(c.qaHead)}`, '');
  c.qa.forEach((x) => L.push(`**${plain(x.q)}** ${plain(x.a)}`, ''));
  while (L[L.length - 1] === '') L.pop();
  return L.join('\n');
}

// llms.txt manifesto region: English first, then every translation, so an LLM
// reading the file sees all languages. Translated pairs carry the English pair.
function llmsBlock() {
  const parts = [llmsLang(en, '## Manifesto (English)')];
  LANGS.filter((l) => l !== 'en').forEach((lang) =>
    parts.push(llmsLang(all[lang], `## Manifesto (${all[lang].name})`)));
  return parts.join('\n\n');
}

function readmeBlock() {
  const L = [
    '> _Generated from [`manifesto/content/en.json`](manifesto/content/en.json) — edit the JSON '
    + '(and its siblings for other languages), then run `node manifesto/build.js`. Do not edit this section by hand._',
    '',
  ];
  en.lede.forEach((p) => { L.push(inline(p, { emphasis: 'md', links: 'md' })); L.push(''); });
  L.push(`## ${inline(en.sectionHead, { emphasis: 'md', links: 'md' })}`, '');
  en.shifts.forEach((s, i) => {
    const gi = groupOpening(i);
    if (gi >= 0) {
      const g = en.groups[gi];
      L.push(`**${g.label}** — ${g.by} [${g.link}](${g.href})`, '');
    }
    L.push(`### ${i + 1}. ${s.from} → ${s.to}`);
    L.push(inline(s.note, { emphasis: 'md', links: 'md' }), '');
  });
  if (en.systemNote) [].concat(en.systemNote).forEach((p) => L.push(inline(p, { emphasis: 'md', links: 'md' }), ''));
  L.push(`## ${inline(en.qaHead, { emphasis: 'md', links: 'md' })}`, '');
  en.qa.forEach((x) => {
    L.push(`> **${inline(x.q, { emphasis: 'md', links: 'md' })}**`, '');
    L.push(inline(x.a, { emphasis: 'md', links: 'md' }), '');
  });
  while (L[L.length - 1] === '') L.pop();
  return L.join('\n');
}

// Standalone, downloadable Markdown of one language's manifesto — the whole
// page as a clean .md (title, subtitle, lede, the five shifts, Q&A). On
// translated pages the canonical English pair follows each localized pair in
// parens, mirroring the on-page gloss.
function manifestoMd(c) {
  const md = (s) => inline(s, { emphasis: 'md', links: 'md' });
  const L = [];
  L.push('# Agentic Shift', '');
  L.push(`_${md(c.hero.subtitle)}_`, '');
  c.lede.forEach((p) => { L.push(md(p)); L.push(''); });
  L.push(`## ${md(c.sectionHead)}`, '');
  c.shifts.forEach((s, i) => {
    const gi = groupOpening(i);
    if (gi >= 0) {
      const loc = localGroup(c, gi);
      L.push(`**${md(loc.label)}** — ${md(loc.by)} [${md(loc.link)}](${en.groups[gi].href})`, '');
    }
    const n = String(i + 1).padStart(2, '0');
    const gloss = c.lang === 'en' ? '' : ` (${en.shifts[i].from} → ${en.shifts[i].to})`;
    L.push(`### ${n}. ${s.from} → ${s.to}${gloss}`);
    L.push(md(s.note), '');
  });
  if (c.systemNote) [].concat(c.systemNote).forEach((p) => L.push(md(p), ''));
  L.push(`## ${md(c.qaHead)}`, '');
  c.qa.forEach((x) => {
    L.push(`### ${md(x.q)}`);
    L.push(md(x.a), '');
  });
  L.push('---', '');
  L.push(`${md(c.foot.by)} [Alexey Krivitsky](https://www.linkedin.com/in/alexeykrivitsky/) · ${ORIGIN}${c.dir}`, '');
  return L.join('\n');
}

// Replace the region between MANIFESTO markers; never write if markers absent.
function writeMarked(rel, block) {
  const file = path.join(ROOT, rel);
  const txt = read(file);
  const re = /<!-- MANIFESTO:START[\s\S]*?MANIFESTO:END -->/;
  if (!re.test(txt)) { console.warn(`! ${rel}: no MANIFESTO markers — skipped`); return; }
  // Short, invisible boundary markers; the human-facing "generated from …"
  // note is emitted as the first visible line of the block (a real MD link).
  const wrapped = `<!-- MANIFESTO:START -->\n\n${block}\n\n<!-- MANIFESTO:END -->`;
  const next = txt.replace(re, wrapped);
  if (next !== txt) { fs.writeFileSync(file, next); written.push(rel); }
}

// ── en → translation parity ───────────────────────────────────────────
// en.json is canonical, so anything added to it — a Q&A, a shift, a lede
// paragraph — must land in every translation, or the translated pages quietly
// keep serving an older manifesto. (That is exactly how the /community Q&A ran
// English-only for weeks.) This reports precisely what each language lacks and
// exits non-zero; the files are still written, so you can keep iterating while
// the translations catch up.
function parityDrift() {
  const COUNTED = ['lede', 'groups', 'shifts', 'systemNote', 'qa'];
  const drift = [];
  for (const lang of LANGS.filter((l) => l !== 'en')) {
    const c = all[lang];
    const gaps = [];
    Object.keys(en).filter((k) => !(k in c)).forEach((k) => gaps.push(`no "${k}"`));
    Object.keys(en.meta).filter((k) => !(k in (c.meta || {}))).forEach((k) => gaps.push(`no meta.${k}`));
    COUNTED.forEach((k) => {
      const want = [].concat(en[k] || []).length;
      const got = [].concat(c[k] || []).length;
      if (got < want) gaps.push(`${k} ${got}/${want}`);
    });
    // Groups also need their per-field copy — a group present but missing its
    // localized `label`/`by`/`link` silently renders the English words.
    en.groups.forEach((g, gi) => {
      const loc = (c.groups || [])[gi];
      if (!loc) return;
      ['label', 'by', 'link'].filter((k) => !loc[k]).forEach((k) => gaps.push(`groups[${gi}].${k}`));
    });
    if (gaps.length) drift.push(`  ${lang}: ${gaps.join(' · ')}`);
  }
  return drift;
}

// ── write ─────────────────────────────────────────────────────────────
const written = [];

for (const lang of LANGS) {
  const c = all[lang];
  // Output path comes from `dir`, not from the language code — they usually
  // match (`de` → /de/) but need not. Czech ships at /cz/ (the country code
  // people recognise) while its language code stays the ISO 639-1 `cs` used by
  // lang=/hreflang=. `dir: "/"` (en) lands at public/index.html.
  const dest = path.join(PUBLIC, c.dir.replace(/^\/+|\/+$/g, ''), 'index.html');
  fs.mkdirSync(path.dirname(dest), { recursive: true });
  fs.writeFileSync(dest, render(c));
  written.push(path.relative(ROOT, dest));
  const mdDest = path.join(path.dirname(dest), `agentic-shift-${c.lang}.md`);
  fs.writeFileSync(mdDest, manifestoMd(c));
  written.push(path.relative(ROOT, mdDest));
}

fs.writeFileSync(path.join(PUBLIC, 'sitemap.xml'), sitemap());
written.push('public/sitemap.xml');

writeMarked('public/llms.txt', llmsBlock());
writeMarked('README.md', readmeBlock());

console.log(`Built ${LANGS.length} language(s):\n${written.map((w) => `  ${w}`).join('\n')}`);
if (missing.length) {
  console.log(`\nNot built (no content/<lang>.json yet): ${missing.join(', ')}`);
}

const drift = parityDrift();
if (drift.length) {
  console.error(`\n✗ TRANSLATION DRIFT — en.json carries content these languages lack:\n${drift.join('\n')}\n`
    + `\n  en.json is canonical: add the missing entries to manifesto/content/<lang>.json,\n`
    + `  then rebuild. The pages above were still written — they are just incomplete.`);
  process.exitCode = 1;
} else {
  console.log(`\n✓ all ${LANGS.length - 1} translations match en.json`);
}
