#!/usr/bin/env node
/**
 * Manifesto generator — zero dependencies, plain Node.
 *
 * Edit content in manifesto/content/*.json, then run:
 *   node manifesto/build.js
 *
 * Generates (never hand-edit these):
 *   public/index.html            EN
 *   public/<lang>/index.html     each translation
 *
 * Deliberately does NOT generate public/llms.txt or the README manifesto
 * section. Both are hand-written and carry material that has no source in
 * these JSON files (llms.txt has its own summary, Meetups and Links
 * sections; the README has its own emphasis and structure). Generating them
 * would clobber good prose to solve a drift risk that only bites when the
 * manifesto text itself changes — which is rare, and caught by review.
 *
 * The canonical English pair shown under each translated pair is read from
 * en.json at build time — translations never restate it, so it cannot drift.
 */

const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const CONTENT = path.join(__dirname, 'content');
const PUBLIC = path.join(ROOT, 'public');
const ORIGIN = 'https://agentic-shift.com';
const BANNER = '<!-- GENERATED by manifesto/build.js from manifesto/content/{lang}.json — do not edit by hand. -->';

// Order defines the language switcher order. `en` must come first: it is the
// canonical source for the English pairs and for llms.txt / README.
// A language appears on the site only once content/<lang>.json exists, so a
// translation in progress is simply absent rather than half-rendered.
const ALL_LANGS = ['en', 'de', 'fr', 'es', 'uk', 'ja'];
const LANGS = ALL_LANGS.filter((l) => fs.existsSync(path.join(__dirname, 'content', `${l}.json`)));

const missing = ALL_LANGS.filter((l) => !LANGS.includes(l));
if (!LANGS.includes('en')) throw new Error('content/en.json is required — it is the canonical source.');

const OG_LOCALE = {
  en: 'en_US', de: 'de_DE', fr: 'fr_FR', es: 'es_ES', uk: 'uk_UA', ja: 'ja_JP',
};

// Wording for the switcher's aria-label, per language.
const LANGBAR_LABEL = {
  en: 'Language', de: 'Sprache', fr: 'Langue', es: 'Idioma',
  uk: 'Мова', ja: '言語',
};

const read = (p) => fs.readFileSync(p, 'utf8');
const load = (lang) => JSON.parse(read(path.join(CONTENT, `${lang}.json`)));

const all = Object.fromEntries(LANGS.map((l) => [l, load(l)]));
const en = all.en;
const template = read(path.join(__dirname, 'template.html'));

const esc = (s) => String(s)
  .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
  .replace(/"/g, '&quot;');

function hreflang() {
  const rows = LANGS.map((l) =>
    `  <link rel="alternate" hreflang="${l}" href="${ORIGIN}${all[l].dir}">`);
  rows.push(`  <link rel="alternate" hreflang="x-default" href="${ORIGIN}${en.dir}">`);
  return rows.join('\n');
}

function langbar(current) {
  return LANGS.map((l) => {
    const c = all[l];
    const active = l === current ? ' aria-current="page"' : '';
    return `      <a href="${c.dir}" hreflang="${l}" lang="${l}"${active}>${esc(c.name)}</a>`;
  }).join('\n');
}

function pair(s, ref, isEn) {
  // English page: plain pair, no gloss (stays identical to the canonical page).
  if (isEn) {
    return `<p class="pair"><span class="from">${esc(s.from)}</span>`
      + `<span class="arrow" aria-hidden="true">→</span>`
      + `<span class="to">${esc(s.to)}</span></p>`;
  }
  // Translated page: each term stacks its canonical English word directly
  // beneath it — sourced from en.json, so the gloss can never drift.
  const term = (cls, word, gloss) =>
    `<span class="term"><span class="${cls}">${esc(word)}</span>`
    + `<span class="pair-en" lang="en">${esc(gloss)}</span></span>`;
  return `<p class="pair">`
    + term('from', s.from, ref.from)
    + `<span class="arrow" aria-hidden="true">→</span>`
    + term('to', s.to, ref.to)
    + `</p>`;
}

function shifts(c) {
  const isEn = c.lang === 'en';
  return c.shifts.map((s, i) => {
    const n = String(i + 1).padStart(2, '0');
    return `      <li class="shift">
        <span class="n" aria-hidden="true">${n}</span>
        <div class="shift-body">
          ${pair(s, en.shifts[i], isEn)}
          <p class="note">${s.note}</p>
        </div>
      </li>`;
  }).join('\n\n');
}

const lede = (c) => c.lede.map((p) => `    <p class="lede">${p}</p>`).join('\n\n');

const qa = (c) => c.qa.map((x) =>
  `    <p class="q-head"><span class="p" aria-hidden="true">&gt;</span> ${esc(x.q)}</p>\n\n    <p class="lede">${x.a}</p>`
).join('\n\n');

function render(c) {
  const map = {
    LANG: c.lang,
    DIR: c.dir,
    OG_LOCALE: OG_LOCALE[c.lang],
    LANGBAR_LABEL: esc(LANGBAR_LABEL[c.lang]),
    LANGBAR: langbar(c.lang),
    HREFLANG: hreflang(),
    META_TITLE: esc(c.meta.title),
    META_DESCRIPTION: esc(c.meta.description),
    META_KEYWORDS: esc(c.meta.keywords),
    META_OG_TITLE: esc(c.meta.ogTitle),
    META_OG_DESCRIPTION: esc(c.meta.ogDescription),
    META_SCHEMA_DESCRIPTION: esc(c.meta.schemaDescription),
    META_LLMS_TITLE: esc(c.meta.llmsTitle),
    HEADLINE_LEAD: esc(c.hero.headlineLead),
    HEADLINE_GLITCH: esc(c.hero.headlineGlitch),
    SUBTITLE: esc(c.hero.subtitle),
    LEDE: lede(c),
    SECTION_HEAD: c.sectionHead,
    SHIFTS: shifts(c),
    QA: qa(c),
    FOOT_BY: esc(c.foot.by),
    FOOT_CTA: esc(c.foot.cta),
  };

  let out = template;
  for (const [k, v] of Object.entries(map)) {
    out = out.split(`{{${k}}}`).join(v);
  }

  const left = out.match(/\{\{[A-Z_]+\}\}/g);
  if (left) throw new Error(`${c.lang}: unreplaced placeholders: ${[...new Set(left)].join(', ')}`);

  return out.replace('<!DOCTYPE html>', `<!DOCTYPE html>\n${BANNER.replace('{lang}', c.lang)}`);
}

// ── write ─────────────────────────────────────────────────────────────
const written = [];

for (const lang of LANGS) {
  const c = all[lang];
  const dest = lang === 'en'
    ? path.join(PUBLIC, 'index.html')
    : path.join(PUBLIC, lang, 'index.html');
  fs.mkdirSync(path.dirname(dest), { recursive: true });
  fs.writeFileSync(dest, render(c));
  written.push(path.relative(ROOT, dest));
}

console.log(`Built ${LANGS.length} language(s):\n${written.map((w) => `  ${w}`).join('\n')}`);
if (missing.length) {
  console.log(`\nNot built (no content/<lang>.json yet): ${missing.join(', ')}`);
}
